### ISSUE TITLE
Can't npm install

### ISSUE THREAD

**Issue by FraserEmbrey** [brendan-ward/gatsby-starter-mapbox#11]
I get an error every time I try to run npm install.

[2020-12-16T13_11_33_060Z-debug.log](https://github.com/brendan-ward/gatsby-starter-mapbox/files/5702864/2020-12-16T13_11_33_060Z-debug.log)

**Comment by brendan-ward** [comment]
Looks like you are running into an issue building / installing the [`sharp`](https://github.com/lovell/sharp) dependency, which is outside our control here.

The Gatsby docs for [`gatsby-plugin-sharp`](https://www.gatsbyjs.com/plugins/gatsby-plugin-sharp/) or [`gatsby-transformer-sharp`](https://www.gatsbyjs.com/plugins/gatsby-transformer-sharp/) may be of use here, since those are the ones pulling in `sharp`.

In case it helps, I've not had issues installing `sharp` on MacOS (x86_64 not ARM) in NodeJS 10 or 12.  Have not tried NodeJS 15.
